spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xmk?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    password: redis2020
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # 密匙KEY
  secret: JwtSecret
  # 过期时间(这里设定为豪秒)
  expire: 600000
  # HeaderKEY
  header: JWTDemo
server:
  port: 8888